# Generated by Django 4.2.11 on 2024-03-22 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('assistant', 'Assistant'), ('chercheur', ' Chercheur'), ('user', 'User')], default='user', max_length=20, verbose_name='role'),
        ),
    ]
