# Generated by Django 5.0.2 on 2024-03-15 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chercheur',
            fields=[
                ('id_chercheur', models.AutoField(primary_key=True, serialize=False)),
                ('nom_chercheur', models.CharField(max_length=50)),
                ('prenom_chercheur', models.CharField(max_length=50)),
                ('etablissement', models.CharField(max_length=50)),
                ('diplome', models.CharField(choices=[('Licence', 'Licence'), ('Master', 'Master'), ('Ingéniorat', 'Ingéniorat'), ('Doctorat', 'Doctorat'), ('Diplôme dÉtudes Supérieures', 'Diplôme dÉtudes Supérieures'), ('Diplôme de Formation Approfondie', 'Diplôme de Formation Approfondie'), ('Diplôme dÉtudes Approfondies', 'Diplôme dÉtudes Approfondies'), ('Autre', 'Autre')], max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('tel', models.CharField(max_length=50)),
                ('dblp_lien', models.CharField(max_length=50)),
                ('research_gate_lien', models.CharField(max_length=50)),
                ('google_scholar_lien', models.CharField(max_length=50)),
                ('site_web', models.CharField(max_length=50)),
                ('grade_ensignement', models.CharField(choices=[('Professeur', 'Professeur'), ('MCA', 'MCA'), ('MCB', 'MCB'), ('MAA', 'MAA'), ('MAB', 'MAB'), ('Doctorant', 'Doctorant'), ('NULL', 'NULL')], max_length=50)),
                ('grade_recherche', models.CharField(choices=[('Directeur de recherche', 'Directeur de recherche'), ('Maître de recherche', 'Maître de recherche'), ('NULL', 'NULL')], max_length=50)),
                ('Qualite', models.CharField(choices=[('Enseignant-Chercheur', 'Enseignant-Chercheur'), ('Chercheur', 'Chercheur'), ('Doctorant', 'Doctorant'), ('Autre', 'Autre')], max_length=50)),
                ('h_index', models.CharField(max_length=50)),
                ('equipe', models.CharField(max_length=50)),
                ('statut', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Chercheurs',
            },
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id_projet', models.AutoField(primary_key=True, serialize=False)),
                ('titre_projet', models.CharField(max_length=50)),
                ('chef_de_projet', models.CharField(max_length=50)),
                ('domain', models.CharField(max_length=50)),
                ('année_debut', models.IntegerField()),
                ('année_fin', models.IntegerField()),
            ],
            options={
                'db_table': 'projets',
            },
        ),
    ]
