# Generated by Django 5.0.2 on 2024-03-15 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmcs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='année_debut',
            field=models.IntegerField(db_column='année_debut'),
        ),
        migrations.RenameField(
            model_name='projet',
            old_name='année_debut',
            new_name='annee_debut',
        ),
        migrations.AlterField(
            model_name='projet',
            name='année_fin',
            field=models.IntegerField(db_column='année_fin'),
        ),
        migrations.RenameField(
            model_name='projet',
            old_name='année_fin',
            new_name='annee_fin',
        ),
    ]
