# Generated by Django 5.0.2 on 2024-03-15 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmcs', '0002_alter_projet_année_debut_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projet',
            old_name='domain',
            new_name='domaine',
        ),
    ]
