# Generated by Django 5.0.2 on 2024-03-15 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmcs', '0003_rename_domain_projet_domaine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encadrement',
            fields=[
                ('id_encadrement', models.AutoField(primary_key=True, serialize=False)),
                ('type_encadrement', models.CharField(choices=[('PFE', 'PFE'), ('Master', 'Master'), ('Doctorat', 'Doctorat'), ('Autre', 'Autre')], default=None, max_length=50)),
                ('intitule', models.CharField(default=None, max_length=50)),
                ('role_chercheur', models.CharField(choices=[('encadreur', 'encadreur'), ('co_encadreur', 'co_encadreur')], max_length=50)),
                ('annee_debut', models.IntegerField(db_column='année_debut')),
                ('annee_fin', models.IntegerField(db_column='année_fin')),
                ('nom_prenom_etd1', models.CharField(max_length=50)),
                ('nom_prenom_etd2', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'encadrements',
            },
        ),
    ]
