# Generated by Django 5.0.2 on 2024-03-15 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmcs', '0004_encadrement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encadrement',
            name='type_encadrement',
            field=models.CharField(choices=[('PFE', 'PFE'), ('Master', 'Master'), ('Doctorat', 'Doctorat'), ('Autre', 'Autre')], max_length=50),
        ),
    ]
