# Generated by Django 5.0.2 on 2024-03-15 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmcs', '0005_alter_encadrement_type_encadrement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encadrement',
            name='role_chercheur',
            field=models.CharField(choices=[('encadreur', 'encadreur'), ('co_encadreur', 'co_encadreur')], db_column='role_chercheur', max_length=50),
        ),
        migrations.RenameField(
            model_name='encadrement',
            old_name='role_chercheur',
            new_name='role_ch',
        ),
    ]
