# Generated by Django 5.0.2 on 2024-03-16 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmcs', '0006_alter_encadrement_role_chercheur_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encadrement',
            name='role_ch',
        ),
        migrations.AddField(
            model_name='encadrement',
            name='role_chercheur',
            field=models.CharField(choices=[('encadreur', 'Encadreur'), ('co_encadreur', 'Co_encadreur')], default='', max_length=50),
        ),
    ]
