# Generated by Django 5.0.2 on 2024-03-16 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmcs', '0007_remove_encadrement_role_ch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conf_journal',
            fields=[
                ('acronyme', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('p_type', models.CharField(choices=[('Conférence', 'Conférence'), ('Journal', 'Journal')], max_length=50)),
                ('periodicite', models.CharField(choices=[('Ad hoc', 'Ad hoc'), ('Continuelle', 'Continuelle'), ('Saisonnière', 'Saisonnière'), ('Mensuelle', 'Mensuelle'), ('Bimensuelle', 'Bimensuelle'), ('Trimestrielle', 'Trimestrielle'), ('Semestrielle', 'Semestrielle'), ('Annuelle', 'Annuelle'), ('Biennale', 'Biennale'), ('Triennale', 'Triennale'), ('Quadriennale', 'Quadriennale'), ('Quinquemestrielle', 'Quinquemestrielle'), ('Hebdomadaire', 'Hebdomadaire'), ('Biquadrimestrielle', 'Biquadrimestrielle'), ('Spéciale/Supplémentaire', 'Spéciale/Supplémentaire'), ('autre', 'autre')], max_length=50)),
                ('lien', models.CharField(max_length=50)),
                ('core_classification', models.CharField(choices=[('A*', 'A*'), ('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=50)),
                ('scimago_classification', models.CharField(choices=[('Q1', 'Q1'), ('Q2', 'Q2'), ('Q3', 'Q3'), ('Q4', 'Q4')], max_length=50)),
                ('qualis_classification', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('B3', 'B3'), ('B4', 'B4'), ('B5', 'B5'), ('C', 'C')], max_length=50)),
                ('dgrsdt_classification', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('Autre', 'Autre')], max_length=50)),
            ],
            options={
                'db_table': 'conf_journal',
            },
        ),
    ]
