# Generated by Django 5.0.2 on 2024-03-20 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmcs', '0009_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=250)),
                ('num_tel', models.CharField(max_length=50)),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Assistant', 'Assistant'), ('Chercheur', 'Chercheur')], max_length=50)),
                ('chercheur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lmcs.chercheur')),
            ],
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
