# Generated by Django 5.0.2 on 2024-03-20 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmcs', '0010_utilisateur_delete_customuser'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='utilisateur',
            table='utilisateur',
        ),
    ]
