# Generated by Django 5.0.2 on 2024-03-21 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmcs', '0011_alter_utilisateur_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Utilisateur',
        ),
    ]
