# Generated by Django 5.0.2 on 2024-03-21 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmcs', '0012_delete_utilisateur'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role_user', models.CharField(choices=[('Admin', 'Admin'), ('Assistent', 'Assistent'), ('Chercheur', 'Chercheur')], max_length=60)),
                ('chercheur_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lmcs.chercheur')),
            ],
            options={
                'db_table': 'utilisateur',
            },
        ),
    ]
