# Generated by Django 5.0.2 on 2024-03-21 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmcs', '0013_utilisateur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='chercheur_id',
            field=models.OneToOneField(db_column='chercheur_id', on_delete=django.db.models.deletion.CASCADE, to='lmcs.chercheur'),
        ),
    ]
