# Generated by Django 5.0.2 on 2024-03-22 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmcs', '0014_alter_utilisateur_chercheur_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='conf_journal',
            name='Conf_Journal_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='conf_journal',
            name='acronyme',
            field=models.CharField(max_length=50),
        ),
    ]
